app = "stockmarketsimulator"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"  # Tell Fly to use your custom Dockerfile

[processes]
  app = "bun run src/server/server.ts"

[[services]]
  # Ties the 'app' process to port 3000
  processes = ["app"]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.ports]]
    handlers = ["http"]
    port = 80

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
