app = "stockmarketsimulator"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"

[processes]
  app = "bun run src/server/server.ts"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.ports]]
    handlers = ["http"]
    port = 80

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
